version: '3.8'

# Production overrides for docker-compose.yml
services:
  postgres:
    environment:
      POSTGRES_DB: trading_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123} --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  backend:
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/trading_db
      - REDIS_URL=redis://${REDIS_PASSWORD:-redis123}@redis:6379
      - ENVIRONMENT=production
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes: []
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  frontend:
    environment:
      - NEXT_PUBLIC_API_URL=https://your-domain.com
      - NODE_ENV=production
    command: node server.js
    volumes: []
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates volume in production
      # - ./ssl:/etc/nginx/ssl:ro
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'
